"""Scan the Wikipedia grape-lexicon cache and produce a coverage report.

Reads:  raw/wikipedia/grapes/{fr,en,es,nl}/*.json
Writes: raw/wikipedia/missing.md

A slug counts as covered in a locale when its cache file exists and
contains neither `missing: true` nor an `error` key. Slugs are bucketed
into full (4/4) / partial (1-3) / missing-everywhere (0). Missing-
everywhere slugs are further classified heuristically:

  - AOC-compound: slug begins with an AOC name fragment (`aoc-`,
    `pouilly-`, `cotes-du-`, …) — these are extraction artefacts where
    the cahier parser glued the appellation header onto the grape name.
  - colour-variant compound: slug contains both `tuile`/`gris`/`blanc`/
    `rose` and a known grape family (`clairette`, `pinot`, …).
  - true miss: everything else — obscure regional varieties with no
    Wikipedia entry in any of the four locales.
"""

from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / "raw" / "wikipedia" / "grapes"
FR_EXTRACTED = ROOT / "raw" / "inao" / "cahier-extracted"
ES_EXTRACTED = ROOT / "raw" / "es" / "pliegos-extracted"
LOCALES = ("fr", "en", "es", "nl")
REPORT = ROOT / "raw" / "wikipedia" / "missing.md"


def _corpus_slugs() -> set[str]:
    """Slugs actually referenced by the current FR + ES corpus. Stale cache
    files that no longer match either corpus are ignored."""
    out: set[str] = set()
    for src in (FR_EXTRACTED, ES_EXTRACTED):
        if not src.exists():
            continue
        for jp in src.glob("*.json"):
            if jp.name.startswith("_"):
                continue
            rec = json.loads(jp.read_text(encoding="utf-8"))
            for d in (rec.get("grapes") or {}).get("details") or []:
                if d.get("slug"):
                    out.add(d["slug"])
    return out

_AOC_COMPOUND_PREFIXES = (
    "aoc-",
    "pouilly-sur-loire-",
    "pouilly-fume-",
    "cabrieres-",
    "cotes-du-roussillon-villages-",
    "cotes-du-rhone-villages-",
    "rose-d-anjou-",
    "saint-saturnin-",
    "abymes-",
    "blanc-fume-de-pouilly-",
    "vic-bilh-",
)
_AOC_COMPOUND_SUBSTRINGS = (
    "-blanc-clairette-",
    "-alicante-henri-",
    "blanc-alicante-henri-",
    "blanc-clairette-",
)
_MUSCAT_FAMILY = {
    "muscat-a-petits-grains",
    "muscat-a-petits-grains-roses",
    "muscat-a-petits-grains-rouges",
}


def _is_covered(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return False
    if data.get("missing"):
        return False
    if data.get("error"):
        return False
    return bool(data.get("extract"))


def _classify_miss(slug: str) -> str:
    if slug in _MUSCAT_FAMILY:
        return "aoc-compound"
    for prefix in _AOC_COMPOUND_PREFIXES:
        if slug.startswith(prefix):
            return "aoc-compound"
    for sub in _AOC_COMPOUND_SUBSTRINGS:
        if sub in slug:
            return "aoc-compound"
    if re.match(r"^(tuile|blanc|gris|rose)-(clairette|pinot|grenache|muscat)", slug):
        return "colour-variant"
    return "true-miss"


def main() -> int:
    if not CACHE.exists():
        print(f"error: {CACHE} missing — run scripts/02b_fetch_grape_lexicon.py first", file=sys.stderr)
        return 1

    slugs = _corpus_slugs()
    if not slugs:
        print("error: no grape slugs found in FR/ES corpus", file=sys.stderr)
        return 1

    coverage: dict[str, list[str]] = {}
    for slug in sorted(slugs):
        covered = [lang for lang in LOCALES if _is_covered(CACHE / lang / f"{slug}.json")]
        coverage[slug] = covered

    full = [s for s, c in coverage.items() if len(c) == 4]
    partial = [s for s, c in coverage.items() if 0 < len(c) < 4]
    missing = [s for s, c in coverage.items() if not c]

    buckets: dict[str, list[str]] = {"aoc-compound": [], "colour-variant": [], "true-miss": []}
    for slug in missing:
        buckets[_classify_miss(slug)].append(slug)
    miss_counts = Counter({k: len(v) for k, v in buckets.items()})

    lines: list[str] = []
    lines.append("# Wikipedia grape-article coverage report")
    lines.append("")
    lines.append("Generated by `scripts/audit_grape_coverage.py` from the stage-02b cache. "
                 "Refresh: `uv run scripts/02b_fetch_grape_lexicon.py` then "
                 "`uv run scripts/audit_grape_coverage.py`.")
    lines.append("")
    lines.append(f"- {len(full)} slugs resolved in all four locales (fr/en/es/nl)")
    lines.append(f"- {len(partial)} slugs partially covered")
    lines.append(f"- {len(missing)} slugs missing in *all* four locales")
    lines.append(f"- {len(slugs)} slugs total (FR cahiers ∪ ES pliegos)")
    lines.append("")
    lines.append("## Missing in all four locales")
    lines.append("")
    lines.append(f"### AOC-compound slugs (extraction artefacts; not real grape names) — {miss_counts['aoc-compound']}")
    lines.append("")
    for s in buckets["aoc-compound"]:
        lines.append(f"- {s}")
    lines.append("")
    lines.append(f"### Colour-variant compounds — {miss_counts['colour-variant']}")
    lines.append("")
    for s in buckets["colour-variant"]:
        lines.append(f"- {s}")
    lines.append("")
    lines.append(f"### True misses (obscure local varieties or recent crossings without a Wikipedia entry) — {miss_counts['true-miss']}")
    lines.append("")
    for s in buckets["true-miss"]:
        lines.append(f"- {s}")
    lines.append("")
    lines.append("## Partial coverage")
    lines.append("")
    lines.append("| slug | fr | en | es | nl |")
    lines.append("|---|---|---|---|---|")
    for slug in partial:
        cells = ["✓" if lang in coverage[slug] else "·" for lang in LOCALES]
        lines.append(f"| {slug} | {cells[0]} | {cells[1]} | {cells[2]} | {cells[3]} |")
    lines.append("")

    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {REPORT.relative_to(ROOT)}: full={len(full)} partial={len(partial)} missing={len(missing)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
